version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 10
  reviewers:
  - DEcSENT
  labels:
  - dependencies
  ignore:
  - dependency-name: com.diffplug.spotless:spotless-plugin-gradle
    versions:
    - 5.9.0
