language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - android-27
  - build-tools-27.0.3
  - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27"

install:
  - chmod +x ./gradlew

script: ./gradlew clean assembleDebug
